// <auto-generated />
using System;
using ECommerce.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.DataAccess.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20260218014538_AddProductVariantIsActive")]
    partial class AddProductVariantIsActive
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ECommerce.Models.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Kadın Ayakkabı"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Erkek Ayakkabı"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Çocuk Ayakkabı"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Spor",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Topuklu",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Günlük",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Spor",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 8,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Klasik",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 9,
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Günlük",
                            ParentCategoryId = 2
                        },
                        new
                        {
                            Id = 10,
                            DisplayOrder = 1,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Spor",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 11,
                            DisplayOrder = 2,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Okul",
                            ParentCategoryId = 3
                        },
                        new
                        {
                            Id = 12,
                            DisplayOrder = 3,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Günlük",
                            ParentCategoryId = 3
                        });
                });

            modelBuilder.Entity("ECommerce.Models.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("GuestAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GuestPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommerce.Models.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ECommerce.Models.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailableSizes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("DiscountRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableSizes = "36,37,38,39,40,41",
                            Brand = "Nike",
                            CategoryId = 4,
                            Color = "Beyaz",
                            CreatedDate = new DateTime(2025, 1, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Günlük kullanım için rahat ve şık spor ayakkabı",
                            DiscountRate = 15m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 3499.99m,
                            Name = "Nike Air Max 270",
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 2,
                            AvailableSizes = "36,37,38,39,40",
                            Brand = "Adidas",
                            CategoryId = 4,
                            Color = "Siyah",
                            CreatedDate = new DateTime(2025, 1, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Koşu ve antrenman için ideal spor ayakkabı",
                            DiscountRate = 10m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 4299.99m,
                            Name = "Adidas Ultraboost",
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 3,
                            AvailableSizes = "36,37,38,39,40",
                            Brand = "Hotiç",
                            CategoryId = 5,
                            Color = "Kırmızı",
                            CreatedDate = new DateTime(2025, 1, 16, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Zarif ve şık topuklu ayakkabı",
                            DiscountRate = 20m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 1899.99m,
                            Name = "Hotiç Stiletto",
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = 4,
                            AvailableSizes = "40,41,42,43,44,45",
                            Brand = "Puma",
                            CategoryId = 7,
                            Color = "Lacivert",
                            CreatedDate = new DateTime(2025, 1, 16, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Retro tasarımlı erkek spor ayakkabı",
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 2999.99m,
                            Name = "Puma RS-X",
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 5,
                            AvailableSizes = "40,41,42,43,44",
                            Brand = "New Balance",
                            CategoryId = 7,
                            Color = "Gri",
                            CreatedDate = new DateTime(2025, 1, 17, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Klasik ve rahat erkek spor ayakkabı",
                            DiscountRate = 12m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 3299.99m,
                            Name = "New Balance 574",
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 6,
                            AvailableSizes = "40,41,42,43,44",
                            Brand = "Altınyıldız",
                            CategoryId = 8,
                            Color = "Kahverengi",
                            CreatedDate = new DateTime(2025, 1, 18, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "İş ve özel günler için klasik deri ayakkabı",
                            DiscountRate = 25m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 2499.99m,
                            Name = "Altınyıldız Klasik Deri",
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 7,
                            AvailableSizes = "28,29,30,31,32,33,34,35",
                            Brand = "Kinetix",
                            CategoryId = 10,
                            Color = "Mavi",
                            CreatedDate = new DateTime(2025, 1, 20, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Dayanıklı ve rahat çocuk spor ayakkabısı",
                            DiscountRate = 18m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 899.99m,
                            Name = "Kinetix Çocuk Spor",
                            StockQuantity = 200
                        },
                        new
                        {
                            Id = 8,
                            AvailableSizes = "28,29,30,31,32,33,34,35,36",
                            Brand = "Polaris",
                            CategoryId = 11,
                            Color = "Siyah",
                            CreatedDate = new DateTime(2025, 1, 22, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Okul için uygun siyah ayakkabı",
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 699.99m,
                            Name = "Polaris Okul Ayakkabısı",
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 9,
                            AvailableSizes = "36,37,38,39,40",
                            Brand = "Skechers",
                            CategoryId = 6,
                            Color = "Pembe",
                            CreatedDate = new DateTime(2025, 1, 25, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hafif ve rahat günlük yürüyüş ayakkabısı",
                            DiscountRate = 22m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 1999.99m,
                            Name = "Skechers Go Walk",
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 10,
                            AvailableSizes = "39,40,41,42,43,44,45",
                            Brand = "Converse",
                            CategoryId = 9,
                            Color = "Beyaz",
                            CreatedDate = new DateTime(2025, 1, 28, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "İkonik tasarımlı günlük spor ayakkabı",
                            DiscountRate = 8m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 1799.99m,
                            Name = "Converse Chuck Taylor",
                            StockQuantity = 180
                        },
                        new
                        {
                            Id = 11,
                            AvailableSizes = "36,37,38,39,40",
                            Brand = "Nike",
                            CategoryId = 4,
                            Color = "Siyah",
                            CreatedDate = new DateTime(2025, 2, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Günlük koşu ve yürüyüş",
                            DiscountRate = 5m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 1299.99m,
                            Name = "Nike Revolution 7",
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 12,
                            AvailableSizes = "36,37,38,39,40,41",
                            Brand = "Adidas",
                            CategoryId = 4,
                            Color = "Beyaz",
                            CreatedDate = new DateTime(2025, 2, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hafif koşu ayakkabısı",
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 1499.99m,
                            Name = "Adidas Runfalcon",
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = 13,
                            AvailableSizes = "36,37,38,39",
                            Brand = "Hotiç",
                            CategoryId = 5,
                            Color = "Siyah",
                            CreatedDate = new DateTime(2025, 2, 2, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ofis ve özel günler için",
                            DiscountRate = 15m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 1599.99m,
                            Name = "Hotiç Topuklu Pabuç",
                            StockQuantity = 55
                        },
                        new
                        {
                            Id = 14,
                            AvailableSizes = "36,37,38,39,40",
                            Brand = "Skechers",
                            CategoryId = 6,
                            Color = "Beyaz",
                            CreatedDate = new DateTime(2025, 2, 2, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Platform tabanlı rahat ayakkabı",
                            DiscountRate = 10m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 2199.99m,
                            Name = "Skechers D'lites",
                            StockQuantity = 88
                        },
                        new
                        {
                            Id = 15,
                            AvailableSizes = "40,41,42,43,44",
                            Brand = "Puma",
                            CategoryId = 7,
                            Color = "Beyaz",
                            CreatedDate = new DateTime(2025, 2, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Klasik spor stil",
                            DiscountRate = 20m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 999.99m,
                            Name = "Puma Smash",
                            StockQuantity = 130
                        },
                        new
                        {
                            Id = 16,
                            AvailableSizes = "40,41,42,43,44,45",
                            Brand = "New Balance",
                            CategoryId = 7,
                            Color = "Gri",
                            CreatedDate = new DateTime(2025, 2, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Retro koşu ayakkabısı",
                            DiscountRate = 8m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 2799.99m,
                            Name = "New Balance 530",
                            StockQuantity = 65
                        },
                        new
                        {
                            Id = 17,
                            AvailableSizes = "40,41,42,43,44",
                            Brand = "Altınyıldız",
                            CategoryId = 8,
                            Color = "Siyah",
                            CreatedDate = new DateTime(2025, 2, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sade deri babet",
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 899.99m,
                            Name = "Altınyıldız Babet",
                            StockQuantity = 90
                        },
                        new
                        {
                            Id = 18,
                            AvailableSizes = "28,29,30,31,32,33,34",
                            Brand = "Kinetix",
                            CategoryId = 10,
                            Color = "Kırmızı",
                            CreatedDate = new DateTime(2025, 2, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Saha ve salon için",
                            DiscountRate = 12m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 749.99m,
                            Name = "Kinetix Çocuk Basketbol",
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = 19,
                            AvailableSizes = "28,29,30,31,32,33",
                            Brand = "Polaris",
                            CategoryId = 11,
                            Color = "Lacivert",
                            CreatedDate = new DateTime(2025, 2, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kışlık su geçirmez bot",
                            DiscountRate = 25m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 599.99m,
                            Name = "Polaris Çocuk Bot",
                            StockQuantity = 85
                        },
                        new
                        {
                            Id = 20,
                            AvailableSizes = "39,40,41,42,43,44,45",
                            Brand = "Nike",
                            CategoryId = 9,
                            Color = "Beyaz",
                            CreatedDate = new DateTime(2025, 2, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "İkonik basketbol tarzı",
                            DiscountRate = 5m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 3299.99m,
                            Name = "Nike Air Force 1",
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 21,
                            AvailableSizes = "40,41,42,43,44",
                            Brand = "Adidas",
                            CategoryId = 7,
                            Color = "Mavi",
                            CreatedDate = new DateTime(2025, 2, 6, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Klasik spor ayakkabı",
                            DiscountRate = 10m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 2499.99m,
                            Name = "Adidas Gazelle",
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 22,
                            AvailableSizes = "36,37,38,39,40",
                            Brand = "Hotiç",
                            CategoryId = 5,
                            Color = "Altın",
                            CreatedDate = new DateTime(2025, 2, 6, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Gece ve davet için",
                            DiscountRate = 18m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 2299.99m,
                            Name = "Hotiç Abiye Topuklu",
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = 23,
                            AvailableSizes = "36,37,38,39,40,41",
                            Brand = "Skechers",
                            CategoryId = 6,
                            Color = "Gri",
                            CreatedDate = new DateTime(2025, 2, 7, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Destekli taban teknolojisi",
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 1899.99m,
                            Name = "Skechers Arch Fit",
                            StockQuantity = 72
                        },
                        new
                        {
                            Id = 24,
                            AvailableSizes = "39,40,41,42,43,44",
                            Brand = "Puma",
                            CategoryId = 9,
                            Color = "Kahverengi",
                            CreatedDate = new DateTime(2025, 2, 7, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Retro sneaker",
                            DiscountRate = 15m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 1599.99m,
                            Name = "Puma Suede Classic",
                            StockQuantity = 98
                        },
                        new
                        {
                            Id = 25,
                            AvailableSizes = "36,37,38,39,40,41",
                            Brand = "New Balance",
                            CategoryId = 4,
                            Color = "Bej",
                            CreatedDate = new DateTime(2025, 2, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Unisex günlük spor",
                            DiscountRate = 7m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 2399.99m,
                            Name = "New Balance 327",
                            StockQuantity = 82
                        },
                        new
                        {
                            Id = 26,
                            AvailableSizes = "40,41,42,43,44",
                            Brand = "Altınyıldız",
                            CategoryId = 8,
                            Color = "Bordö",
                            CreatedDate = new DateTime(2025, 2, 8, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "İş ve günlük loafer",
                            DiscountRate = 20m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 1199.99m,
                            Name = "Altınyıldız Loafer",
                            StockQuantity = 68
                        },
                        new
                        {
                            Id = 27,
                            AvailableSizes = "28,29,30,31,32,33,34,35",
                            Brand = "Kinetix",
                            CategoryId = 12,
                            Color = "Yeşil",
                            CreatedDate = new DateTime(2025, 2, 9, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Okul sonrası rahat ayakkabı",
                            DiscountRate = 10m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 549.99m,
                            Name = "Kinetix Çocuk Günlük",
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = 28,
                            AvailableSizes = "28,29,30,31,32,33,34",
                            Brand = "Polaris",
                            CategoryId = 10,
                            Color = "Turuncu",
                            CreatedDate = new DateTime(2025, 2, 9, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hafif ve nefes alan",
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 449.99m,
                            Name = "Polaris Çocuk Spor",
                            StockQuantity = 110
                        },
                        new
                        {
                            Id = 29,
                            AvailableSizes = "40,41,42,43,44,45",
                            Brand = "Nike",
                            CategoryId = 7,
                            Color = "Beyaz",
                            CreatedDate = new DateTime(2025, 2, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vintage basketbol tarzı",
                            DiscountRate = 12m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 2699.99m,
                            Name = "Nike Blazer Mid",
                            StockQuantity = 58
                        },
                        new
                        {
                            Id = 30,
                            AvailableSizes = "36,37,38,39,40,41,42,43,44",
                            Brand = "Converse",
                            CategoryId = 9,
                            Color = "Siyah",
                            CreatedDate = new DateTime(2025, 2, 10, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Platform tabanlı Converse",
                            DiscountRate = 5m,
                            IsActive = true,
                            IsDeleted = false,
                            ListPrice = 2299.99m,
                            Name = "Converse Run Star",
                            StockQuantity = 78
                        });
                });

            modelBuilder.Entity("ECommerce.Models.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("ECommerce.Models.Models.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PriceOverride")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductId1")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId1");

                    b.ToTable("ProductVariants");
                });

            modelBuilder.Entity("ECommerce.Models.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("GuestSessionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("ProductVariantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("ECommerce.Models.Models.Slider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sliders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tüm ürünlerde %50'ye varan indirim fırsatını kaçırmayın.",
                            DisplayOrder = 1,
                            ImageUrl = "\\images\\slider\\100.jpg",
                            IsActive = true,
                            Title = "Yaz İndirimi Başladı!"
                        },
                        new
                        {
                            Id = 2,
                            Description = "2025 Sonbahar/Kış koleksiyonumuzla tarzınızı yenileyin.",
                            DisplayOrder = 2,
                            ImageUrl = "\\images\\slider\\199.jpg",
                            IsActive = true,
                            Title = "Yeni Sezon Ürünleri Geldi!"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Sepette ekstra %10 indirim fırsatını yakalayın.",
                            DisplayOrder = 3,
                            ImageUrl = "\\images\\slider\\336.jpg",
                            IsActive = true,
                            Title = "Sadece Bugün: Ekstra %10 İndirim!"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ECommerce.Models.Models.Category", b =>
                {
                    b.HasOne("ECommerce.Models.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ECommerce.Models.Models.Order", b =>
                {
                    b.HasOne("ECommerce.Models.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("ECommerce.Models.Models.OrderItem", b =>
                {
                    b.HasOne("ECommerce.Models.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Models.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Models.Models.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ECommerce.Models.Models.Product", b =>
                {
                    b.HasOne("ECommerce.Models.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ECommerce.Models.Models.ProductImage", b =>
                {
                    b.HasOne("ECommerce.Models.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Models.Models.Product", null)
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId1");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Models.Models.ProductVariant", b =>
                {
                    b.HasOne("ECommerce.Models.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Models.Models.Product", null)
                        .WithMany("ProductVariants")
                        .HasForeignKey("ProductId1");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerce.Models.Models.ShoppingCart", b =>
                {
                    b.HasOne("ECommerce.Models.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");

                    b.HasOne("ECommerce.Models.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Models.Models.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("ApplicationUser");

                    b.Navigation("Product");

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ECommerce.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ECommerce.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ECommerce.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommerce.Models.Models.Category", b =>
                {
                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("ECommerce.Models.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ECommerce.Models.Models.Product", b =>
                {
                    b.Navigation("ProductImages");

                    b.Navigation("ProductVariants");
                });
#pragma warning restore 612, 618
        }
    }
}
